<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>C.v.</title>
</head>
<body>
    <table border="1">
        <tr>
           <th>S.N.</th>
           <th>Level</th>
           <th>School</th>
           <th>GPA</th>
           <th>Work experience</th>
        </tr>
        <tr>
           <td>1</td>
           <td>SEE</td>
           <td>Sanjiwani Model S.S.</td>
           <td>2.65</td>
           <td rowspan="3">1 month intern of QA</td>
        </tr>
        <tr>
           <td>2</td>
           <td>+2</td>
           <td>Siddhartha e.s.s</td>
           <td>3.31</td>
        </tr>
        <tr>
           <td>3</td>
           <td>Bachelor</td>
           <td>Kabhre multiple campus</td>
           <td>undergraduated</td>
        </tr>
       </table>
</body>
</html>